global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'job'] 
  group_wait: 30s             
  group_interval: 5m          
  repeat_interval: 1h         
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'