# Global Prometheus configuration
global:
  scrape_interval: 15s 
  evaluation_interval: 15s

# Rule files
rule_files:
  - "alert.rules.yml"

# Alerting settings
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job for our custom API server
  - job_name: 'api-server'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:5000']